<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Application\Sonata\NewsBundle\Entity;
use Sonata\NewsBundle\Entity\BasePost as BasePost;
/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Recette", inversedBy="post")
     * @ORM\JoinColumn(name="recette_id", referencedColumnName="id")
     */
    protected $recette;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set recette
     *
     * @param \MealSquare\RecetteBundle\Entity\Recette $recette
     *
     * @return Post
     */
    public function setRecette(\MealSquare\RecetteBundle\Entity\Recette $recette = null)
    {
        $this->recette = $recette;

        return $this;
    }

    /**
     * Get recette
     *
     * @return \MealSquare\RecetteBundle\Entity\Recette
     */
    public function getRecette()
    {
        return $this->recette;
    }
}